### ISSUE TITLE
Can't uninstall AutomaThemely

### ISSUE THREAD

**Issue by 100percentfast** [C2N14/AutomaThemely#11]
Having an issue uninstalling this with Muon Package Manager. I'm using the Python 3.5 version of AT, which I mistakenly installed- I have Python 3.6.

When I try to uninstall, it gives me the following error:

An error occurred while applying changes:
automathemely
installed automathemely package pre-removal script subprocess returned error exit status 1

Any clarification on what I may be doing wrong would be highly appreciated!

**Comment by C2N14** [comment]
Is there any more output before that? Is it in any way related to #8 ?

**Comment by 100percentfast** [comment]
Hey, sorry to waste your time with this, but I managed to get this removed with `apt-get remove`. not sure if it's an error in Muon or in my own use of it, but I'm fairly sure that it removed properly.

I rebooted before trying apt, maybe that was [#8's](https://github.com/C2N14/AutomaThemely/issues/8#issue-411040604) problem? I had a similar issue to begin with.

I'm a bit of a linux newbie here so I must admit I have little to no clue the way things should proceed, but I prefer to do things the right way if there's an option.

Here's the output of the removal process if you'd like to scan and confirm that everything went correctly:
`fast@fast-as-slow:~$ sudo apt-get remove automathemely 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Starting pkgProblemResolver with broken count: 0
Starting 2 pkgProblemResolver with broken count: 0
Done
The following packages were automatically installed and are no longer required:
  amarok-common dh-python fonts-dejavu fonts-dejavu-extra game-data-packager
  game-data-packager-runtime icoutils kde-runtime kde-runtime-data kdelibs-bin
  kdelibs5-plugins kdemultimedia-kio-plugins kdoctools kio-audiocd lame libaio1
  libboost-program-options1.65.1 libclucene-core1v5 libexiv2-14 libexpat1-dev libftgl2
  libglew2.0 libgpgme++2v5 libgpod-common libgpod4 libkactivities6 libkcmutils4
  libkde3support4 libkdeclarative5 libkdesu5 libkdewebkit5 libkdnssd4 libkemoticons4
  libkf5compactdisc5 libkfile4 libkhtml5 libkio5 libkjsapi4 libkjsembed4
  libkmediaplayer4 libknewstuff3-4 libknotifyconfig4 libkntlm4 libkparts4 libkpty4
  libkrosscore4 libktexteditor4 libkxmlrpcclient4 liblastfm1 libmygpo-qt1
  libnl-route-3-200 libntrack-qt4-1 libntrack0 libplasma3 libpolkit-qt-1-1
  libprojectm2v5 libprotobuf10 libpython3-dev libpython3.6-dev libqca2 libqca2-plugins
  libqjson0 libqt4-designer libqt4-opengl libqt4-qt3support libqt4-scripttools
  libqtscript4-core libqtscript4-gui libqtscript4-network libqtscript4-sql
  libqtscript4-uitools libqtscript4-xml libqtwebkit4 libqxt-core0 libqxt-gui0
  libsdl-net1.2 libsgutils2-2 libsolid4 libstreamanalyzer0v5 libstreams0v5
  libtag-extras1 libthreadweaver4 ntrack-module-libnl-0 oxygen-icon-theme
  plasma-scriptengine-javascript projectm-data python-pip-whl python3-astral
  python3-crypto python3-dev python3-keyring python3-keyrings.alt python3-pip
  python3-schedule python3-secretstorage python3-tz python3-tzlocal python3-wheel
  python3.6-dev qml-module-qt-labs-platform
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  automathemely
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 668 kB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 210123 files and directories currently installed.)
Removing automathemely (1.3) ...
Removed /etc/systemd/user/timers.target.wants/automathemely.timer.
dpkg: warning: while removing automathemely, directory '/usr/local/lib' not empty so not removed
dpkg: warning: while removing automathemely, directory '/usr/local/share/applications' not empty so not removed
`

**Comment by C2N14** [comment]
No worries, it's alright :)

Well that's some interesting insight, I do believe it may have been caused by the same issue as #8 , and although I am still not quite sure why it happened I guess I have a potential solution for now...
