### ISSUE TITLE
"Timezone [...] not recognized" error

### ISSUE THREAD

**Issue by neekt** [C2N14/AutomaThemely#25]
I cannot get manual time zones to work. When I manually specify a time zone, I get the following error notification when I try to update sun times from the Automathemely icon right-click menu:

`ERROR: Timezone [...] not recognized`

Where [...] is the name of the time zone I have entered. I'm located in Australia, and I have tried "Australian Eastern Standard Time,' 'AEST', 'UTC+10', and 'Australia' as time zone names, and all of them produce the same error. If I leave 'Time zone name' empty, I get an error saying 'Auto location is not enabled and some manual values are missing.'

Is this a bug, or am I doing something wrong? Auto location seems to work just fine (the only problem here is that it uses the time zone of the VPN server IP I connect to, not my local time zone).

Running Linux Mint 19.1 Cinnamon. Here are my user_settings.json settings: https://pastebin.com/PfnPbKAJ

Thanks for maintaining app, I think it's great!

**Comment by C2N14** [comment]
Hey, thank you for your interest!

This app uses the python module [`astral`](https://github.com/sffjunkie/astral) to calculate the sunrise and sunset times, which also depends on [`pytz`](http://pytz.sourceforge.net/) for its timezones.
[This table from Wikipedia](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List) should do the trick, or also [this](https://stackoverflow.com/questions/13866926/is-there-a-list-of-pytz-timezones) might help.

In your case I believe `Australia/Melbourne` should work ;)

Let me know if you encounter any other issue.
