### ISSUE TITLE
Can't uninstall AutomaThemely

### ISSUE THREAD

**Issue by Kandelai** [C2N14/AutomaThemely#3]
I tried to uninstall this program, but it threw up errors. I think it is trying to uninstall some of the python dependencies, at least that is my best guess, but other programs are dependent on it, so it can't and fails. I even tried a force uninstall, and that did not work. 

Please advise on how to remove this. It is not in your instructions.

**Comment by logix2** [comment]
@Kandelai how did you install it exactly, from which package and on what distro? And what's the error exactly? Do you mean warnings like this: "dpkg: warning: while removing automathemely, directory '/usr/local/lib/python3.6/dist-packages'"? That's just a warning, the package files and the package itself were actually removed.

**Comment by Kandelai** [comment]
You are correct. That was weird because Synaptic was still showing Automathemely still installed, and yes, it was those errors, there were three. I even went out and back into Synaptic and it was there, but now it is not. Must have taken awhile to disappear. 

I used the python3.6-no_deps-automathemely_1.2_all.deb package and I am on Debian unstable running Budgie OS. 

Thanks for your help and quick response.

**Comment by logix2** [comment]
@Kandelai Glad I could help. I'm not the developer of this tool by the way in case you thought that :)

**Comment by C2N14** [comment]
Thank you very much @logix2 for helping @Kandelai :)

Also thanks for the article! That's very nice of you.
